#ifndef PEDRO_GIT_PROJECTS_C_REACT_API_STATUS_H 
#define PEDRO_GIT_PROJECTS_C_REACT_API_STATUS_H

typedef enum {
    TODO_STATUS_PENDING,
    TODO_STATUS_IN_PROGRESS,
    TODO_STATUS_COMPLETED
} Status;

#endif  
